In [7]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)

[[5 6]
 [8 3]]


In [12]:
result_array = array * 10
print(result_array)

[[50 60]
 [80 30]]


In [13]:
array1 = np.arange(4).reshape(2, 2) # (2 x 2)
array2 = np.arange(2) # (1 x 2)

array3 = array1 + array2

print(array3)


[[0 2]
 [2 4]]


### 위와 같은 작업을 브로드케스트라고 한다
. 브로드케스트: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

In [38]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
other_array3 = np.concatenate([array1, array2], axis=1)

print(array3,'\n')
print(other_array3, '\n')

array4 = np.arange(4).reshape(4, 1) # (4 x 1)

print(array3+array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]] 

[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]] 

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


### Numpy의 마스킹 연산
- 마스킹: 각 원소에 대하여 체크합니다.

In [42]:
import numpy as np

array1 = np.arange(16).reshape(4, 4) 
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


### Numpy의 집계 함수


In [51]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값: ", np.max(array))
print("최솟값: ", np.min(array))
print("합계: ", np.sum(array))
print("평균값: ", np.mean(array))
print('\n')
print(array, '\n')

print('합계: ', np.sum(array, axis=0))

최대값:  15
최솟값:  0
합계:  120
평균값:  7.5


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

합계:  [24 28 32 36]
